local function PlayPrank()
	print("We’ve been working day and night,")
Wait(500)
print("Lines of code, it's looking tight,")
Wait(500)
print("You’ve been waiting, hoping for a brand-new thing...")
Wait(500)
print("We said 'soon,' yeah, just you wait,")
Wait(500)
print("PS-MDT, it's looking great,")
Wait(500)
print("Now it's time to drop the news you’ve been craving...")
Wait(500)
print("Never gonna ship V2,")
Wait(500)
print("Never gonna make it through,")
Wait(500)
print("Never gonna fix that bug just like we said we would...")
Wait(500)
print("Never gonna push that patch,")
Wait(500)
print("Never gonna make dispatch match,")
Wait(500)
print("April Fools', you fell for that, you really would!")
Wait(500)
print("We’ve teased and hyped, it’s been so fun,")
Wait(500)
print("But V2’s still a work in progress, oh, we’re not done,")
Wait(500)
print("But here's a little joke to keep you going strong...")
Wait(500)
print("Never gonna ship V2,")
Wait(500)
print("Never gonna see it through,")
Wait(500)
print("Never gonna drop that repo like we said we would...")
Wait(500)
print("Never gonna push that patch,")
Wait(500)
print("Never gonna make dispatch match,")
Wait(500)
print("April Fools', you fell for that, you really would!")
Wait(500)
end

repeat
	Wait(1000)
	PlayPrank()
until false
