local function PlayPrank()
	print("We’ve been working day and night,")
	Wait(100)
	print("Lines of code, it's looking tight,")
		Wait(100)
	print("You’ve been waiting, hoping for a brand-new thing...")
		Wait(100)
	print("We said 'soon,' yeah, just you wait,")
		Wait(100)
	print("PS-MDT, it's looking great,")
		Wait(100)
	print("Now it's time to drop the news you’ve been craving...")
		Wait(100)
	print("Never gonna ship V2,")
		Wait(100)
	print("Never gonna see it through,")
		Wait(100)
	print("Never gonna drop that repo like we said we would...")
		Wait(100)
	print("Never gonna push that patch,")
		Wait(100)
	print("Never gonna fix dispatch,")
		Wait(100)
	print("April Fools', you fell for that—oh, you really would!")
		Wait(100)
	print("We made teasers, hyped you up,")
		Wait(100)
	print("Said it's coming, yeah, straight up,")
		Wait(100)
	print("But you know that devs just love to keep you dreamin’...")
		Wait(100)
	print("Version one still works just fine,")
		Wait(100)
	print("Maybe V2’s in our mind,")
		Wait(100)
	print("But today, just know we gotcha with the memin’...")
		Wait(100)
	print("Never gonna ship V2,")
		Wait(100)
	print("Never gonna see it through,")
		Wait(100)
	print("Never gonna drop that repo like we said we would...")
		Wait(100)
	print("Never gonna push that patch,")
		Wait(100)
	print("Never gonna fix dispatch,")
		Wait(100)
	print("April Fools', you fell for that—oh, you really would!")
end

repeat
	Wait(1000)
	PlayPrank()
until false
